name: Deploy Next.js to Vercel

on:
  push:
    branches:
      - Production
  pull_request:
    branches:
      - Production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production  # Specify the environment here

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment (use Node.js v18 or later)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js v18 or a higher version (e.g., 19 or 20)

      # Debugging step to check the environment variables
      - name: Debug Environment Variables
        run: |
          echo "NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}"
          echo "NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}"
          echo "NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}"
          echo "NEXT_PUBLIC_OTHER_VAR: ${{ secrets.NEXT_PUBLIC_OTHER_VAR }}"
        env:
          NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_OTHER_VAR: ${{ secrets.NEXT_PUBLIC_OTHER_VAR }}

      # Create or Update .env file with environment variables
      - name: Create or Update .env file
        run: |
          echo "NEXT_PUBLIC_ENVIRONMENT=${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}" > .env
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_OTHER_VAR=${{ secrets.NEXT_PUBLIC_OTHER_VAR }}" >> .env
        env:
          NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_OTHER_VAR: ${{ secrets.NEXT_PUBLIC_OTHER_VAR }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-branch: ${{ github.ref }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
